#!/bin/bash

docker build -t alxprd/pagekite -f docker/Dockerfile.pagekite ./docker
docker build -t alxprd/ssh-server -f docker/Dockerfile.ssh-server ./docker
docker build -t alxprd/vpn-server -f docker/Dockerfile.vpn-server ./docker

docker build -t alxprd/ssh-client -f docker/Dockerfile.ssh-client ./docker
docker build -t alxprd/vpn-client -f docker/Dockerfile.vpn-client ./docker
