#!/bin/bash

docker run -it --rm \
    -v /dev/snd:/dev/snd \
    --privileged \
    -v $PWD/scripts/:/scripts/ \
    --name listen \
    --net=container:vpn-server \
    alxprd/listen \
    /scripts/listen
#    ncat -l 2000 -k
#   ncat -l 2000 -k -c 'xargs -n1 echo'
