FROM alxprd/pagekite 

# Install OpenVPN
RUN apt-get install -y openvpn

# Install SSH server
RUN apt-get install -y openssh-server

# Adds user0 for SSH
RUN useradd -ms /bin/bash user0
# Creates a home directory for the user and ensures
# that bash is the default shell.
#USER user0
#WORKDIR /home/user0

WORKDIR /root

RUN apt-get install -y python
